-- USER SQL
CREATE USER "SISACSE" IDENTIFIED BY "123"  
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "SISACSE" QUOTA UNLIMITED ON "SYSTEM";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE ANY PROCEDURE TO "SISACSE" ;
GRANT ALTER SESSION TO "SISACSE" ;
GRANT CREATE ANY SEQUENCE TO "SISACSE" ;
GRANT ALTER ANY TABLE TO "SISACSE" ;
GRANT DELETE ANY TABLE TO "SISACSE" ;
GRANT ALTER ANY SEQUENCE TO "SISACSE" ;
GRANT CREATE TABLE TO "SISACSE" ;
GRANT CREATE ANY JOB TO "SISACSE" ;
GRANT CREATE SEQUENCE TO "SISACSE" ;
GRANT CREATE ANY TABLE TO "SISACSE" ;
GRANT CREATE PROCEDURE TO "SISACSE" ;